# Generated by Django 4.0.6 on 2023-01-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0026_netbox_bgp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgppeergroup',
            name='password',
            field=models.CharField(default='not defined', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='peer_group_password',
            field=models.ForeignKey(default='not defined', on_delete=django.db.models.deletion.PROTECT, related_name='session_password', to='netbox_bgp.bgppeergroup', to_field='password'),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='session_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
