# Generated by Django 4.0.6 on 2023-01-10 13:22

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0073_journalentry_tags_custom_fields'),
        ('netbox_bgp', '0027_bgppeergroup_password_bgpsession_peer_group_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpsession',
            name='peer_group_password',
        ),
        migrations.RemoveField(
            model_name='bgpsession',
            name='session_password',
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('password', models.CharField(max_length=128)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='password',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_bgp.password'),
        ),
        migrations.AlterField(
            model_name='bgppeergroup',
            name='password',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_bgp.password'),
        ),
    ]
