# Generated by Django 4.0.6 on 2023-01-12 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0057_created_datetimefield'),
        ('netbox_bgp', '0028_remove_bgpsession_peer_group_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='password',
            options={'verbose_name_plural': 'Passwords'},
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='vrf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ipam.vrf'),
        ),
    ]
